### PR TITLE
Simplify NodeList.toArray

### PR DESCRIPTION
**Pull request by Munter**

### CODE REVIEW

**Comment by eatonphil** [comment]
While I touted lack of compatibility, I don't really see a reason to make this change. You could make the current line shorter by declaring the array within the for loop. But losing one line (in your proposal) for similar performance and less compatibility doesn't really make sense to me.

**Comment by Munter** [comment]
IE8 is the only browser that doesn't have Array.prototype.slice. Incidentally it also has a very limited implementation of querySelector, which you already depend on.

classList is not supported in IE9 and below, so I'm not sure why compatibility is an argument.

I just thought the name also was about showing off how little you can get away with and still have intact functionality :)

**Comment by eatonphil** [comment]
The focus is not compatibility, but your proposal saved one line of code. I just don't really see the benefit from that. Thanks for the suggestion though!

**Comment by eatonphil** [comment]
Thanks for bringing up the classList lack of support with IE9. I will actually deal with that.

**Comment by Munter** [comment]
:+1:

**Pull request closed without merging**
